name: CI/CD - Node to ECR

on:
#   workflow_run:
#     workflows: ["Terraform CI/CD"]
#     types:
#       - completed
  push:
    branches:
      - main
    paths:
      - './**'
      - '.github/workflows/node.yml'

env:
  NODE_ENV: dev
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test

    #   - name: Build App
    #     run: npm run build

    #   - name: Configure AWS Credentials using OIDC
    #     uses: aws-actions/configure-aws-credentials@v4
    #     with:
    #       role-to-assume: arn:aws:iam::<your-account-id>:role/GitHubActions-NodeWorkflowRole
    #       aws-region: us-east-1

    #   - name: Login to Amazon ECR
    #     run: |
    #       aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    #   - name: Build Docker Image
    #     run: |
    #       docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

    #   - name: Push to ECR
    #     run: |
    #       docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
